# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 오세종
title: Product manager
email: sejong80@gmail.com
website: www.github.com/chris-osj

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  Chris-osj


# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
    안녕하세요. PM 및 팀장 으로 일하고 있는 오세종입니다. AI & Lang Chain 등등 신기술과 최신 트렌드에 관심이 많고 
    새로운 기술을 학습하는 것을 좋아합니다. 팀 전체의 생산성을 높이는 것에 관심이 많습니다.
    
    주 스킬은 <mark>PM 및 솔류션 관리 업무</mark>이며, <mark>다양한 PM 경험과 팀 운영 능력 </mark>을 최대한 발휘 하여 
    업무 수행을 합니다.

content:
  - title: 나만의 커리어 여정
    layout: list
    content:
      - title: 소프트웨어 관련 개발 , PM 으로 성장
        sub_title: 자바 웹 개발로 업무를 시작 하여 현재 PM 및 팀장 업무 수행 중
        caption: 2010.01. ~ 현재
        description: | # this will include new lines to allow paragraphs
          기술 스택
            - <mark>Spring Boot</mark>,<mark>Nginx</mark>,<mark>node.js</mark>,<mark>Junit5</mark>, <mark>Java</mark>, <mark>Javascript</mark>
            - <mark>Jenkins</mark>, <mark>RDBMS</mark>, <mark>Grafana</mark> ,<mark>vue.js</mark> 
            - <mark>Mybatis</mark>, <mark>NoSQL</mark>, <mark>Git</mark>
  - title: Experience # Title for the section
    layout: list # Layout for the section
    content:
      - title: Timbel
        sub_title: web 솔류션별 관리
        caption: 2022.11 ~ 현재
        description: | # this will include new lines to allow paragraphs
          웹개발 팀 팀장  
          - 기획 업무 회의 및 개발 일정 수립
          - 프로젝트 아키텍쳐 설계
          - 개발 업무 협의 진행 및 서버 관리
          - STT , TTS , LLM , SLM 을 이용한 솔루션 관리
          - 신규 솔류션 timblo 런칭
      - title: 한국 클라우드
        sub_title: 팔레트 상담 Application PM
        caption: 2021.07 ~ 2022.10
        description: | # this will include new lines to allow paragraphs
          팔레트(상담 APP) 솔루션 기획(F/E vue , B/E Springboot)
          - 데이터 베이스 설계
          - 프로젝트 오픈 진행 
          - 운영 유지보수 
          - 신규 프로젝트 진행시 팔레트 솔류션 으로 프로젝트 진행 하여 프로젝트 구성 진행
      - title: 메타넷
        sub_title: IPCC PM 및 파트장
        caption: 2019.06 ~ 2021.06
        description: | # this will include new lines to allow paragraphs
          IPCC PM 업무 
          - 신규 사업 오픈 견적 작업
          - 우정사업본부 , 흥국생명, 삼성물산, 모빌리언스 & 올앳 , 11번가 , 쁘띠엘린, 런드리고 , 국가 평생교육진흥원 , 
            퀄슨 , 오호라 , 현대홈쇼핑IM , 코드스테이츠 , 경기도 일자리 재단 , 위매이드 , 에이렌탈서비스 오픈 진행
          - 60여개 IPCC 기술지원 파트장 유지보수 업무
      - title: 한국 코퍼레이션
        sub_title: PM 업무
        caption: 2018.09 ~ 2019.06
        description: | # this will include new lines to allow paragraphs
          상담 APP PM 
          - ABL 생명 해피콜 시스템 PM
          - 각 프로젝트 PM 업무 ,기획 및 테이블 설계
          - 부산 은행 채권관리 시스템 PM
          - 채권관리 시스템 전화기 연동
          - 기획 및 테이블 설계
      - layout: left
      - title: 메타넷
        sub_title: 매트라이프 생명 상담 APP 유지보수 및 PM
        caption: 2014.08 ~ 2018.08
        description: | # this will include new lines to allow paragraphs
          상담 APP 개발 PM 
          - 매트라이프 생명 상담 APP 유지보수 PM
          - 자금세탁방지 프로젝트 개발 진행(AML)
          - 펀드 , 변액 보험 개발 및 유지보수
      - layout: left
        title: CRM뱅크
        sub_title: 매트라이프 생명 상담 APP 개발 및 유지보수
        caption: 2011.08 ~ 2014.07
        description: | # this will include new lines to allow paragraphs
          상담 APP 개발 업무 수행
          - 상담 APP 개발
          - 파트별 유지보수
          - 해피콜 프로젝트 개발 진행
      - title: 아이아스소프트
        sub_title: 병원 솔류션 구축
        caption: 2010.08 ~ 2011.07
        description: | # this will include new lines to allow paragraphs
          병원 프로그램 개발
          - 병원 프로그램 유지보수 진행
          - 병원 DUR 연동 개발
          - 의료기기 연동 개발 (RS232 통신)
      - title: 에듀 모니카
        sub_title: 학원 솔류션 운영
        caption: 2010.05 ~ 2010.07
        description: | # this will include new lines to allow paragraphs
          학원 솔류션 개발
          - 학원 프로그램 유지보수
          - 학원 출석 시스템 유지 보수 진행
          - 출석 문자 발송 개발
          

## Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
